version: '3'

services:
  nest-backend:
    image: nest-backend
    ports:
      - 2053:2053
      - 2083:2083
    volumes:
      - /etc/ssl/server-cert-key:/etc/ssl/server-cert-key

  carcassonne-client:
    image: carcassonne-client
    ports:
      - 443:443
    volumes:
      - /etc/ssl/server-cert-key:/etc/nginx/certs