version: '3'

services:
  nest-backend:
    image: nest-backend
    ports:
      - 80:80
      - 8080:8080

  carcassonne-client:
    image: carcassonne-client
    ports:
      - 443:443
    volumes:
      - /etc/ssl/server-cert-key:/etc/nginx/certs