version: '3'

services:
  nest-backend:
    image: nest-backend
    ports:
      - 3000:3000
      - 3001:3001

  carcassonne-client:
    image: carcassonne-client
    ports:
      - 443:443
    volumes:
      - /etc/ssl/server-cert-key:/etc/nginx/certs